from corelib.htmlgen import *
from corelib.phelix import leafComponent


@leafComponent
def Homepage():
    return mainelement(
        div(
            img(ref="/public/favicon.png", classname="logo"),
            h1("Welcome to Cascada!"),
        ),
        p("this a website fully generated by cascada"),
    )
