from corelib.htmlgen import *
from corelib.phelix import leafComponent


@leafComponent
def Homepage():
    return mainelement(
        h1("Welcome to Cascada!"),
        p("this a website fully generated by cascada")
    )
